Correct old defunct code

diff --git a/source/.i3a/term_font_size b/source/.i3a/term_font_size
--- a/source/.i3a/term_font_size
+++ b/source/.i3a/term_font_size
@@ -3,12 +3,12 @@
 #------------------------------------------------------------------------------
 # Project Name      - i3Config/source/.i3a/term_font_size
 # Started On        - Mon 30 Oct 15:14:16 GMT 2017
-# Last Change       - Wed 11 Nov 16:31:51 GMT 2020
+# Last Change       - Sun 12 Dec 08:42:16 GMT 2021
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #------------------------------------------------------------------------------
 
-CurVer='2020-11-11'
+CurVer='2021-12-12'
 Progrm=${0##*/}
 
 Usage(){
@@ -36,9 +36,11 @@ Err(){
 	[ $1 -eq 1 ] && exit 1
 }
 
-CheckVal(){ [[ $1 =~ ^[0-9]+$ ]] || Err 1 'Invalid expression.'; }
+CheckVal(){
+	[[ $1 =~ ^[0-9]+$ ]] || Err 1 'Invalid expression.'
+}
 
-while [ "$1" ]; do
+while [ -n "$1" ]; do
 	case $1 in
 		--help|-h|-\?)
 			Usage; exit 0 ;;
@@ -65,7 +67,9 @@ while [ "$1" ]; do
 	shift
 done
 
-ChkDep sed
+if ! type -P sed &> /dev/null; then
+	Err 1 "Dependency 'sed' not met."
+fi
 
 Config="$HOME/.config/xfce4/terminal/terminalrc"
 
