Updated i3bar_trans; added simple test

diff --git a/.i3a/i3bar_trans b/.i3a/i3bar_trans
--- a/.i3a/i3bar_trans
+++ b/.i3a/i3bar_trans
@@ -3,7 +3,7 @@
 #----------------------------------------------------------------------------------
 # Project Name      - $HOME/.i3a/i3bar_trans
 # Started On        - Sat 17 Feb 01:34:23 GMT 2018
-# Last Change       - Wed 11 Apr 10:08:21 BST 2018
+# Last Change       - Sat 14 Apr 20:15:12 BST 2018
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -17,14 +17,19 @@
 # allowed. 0 is invisible, and 1 is completely opaque.
 #----------------------------------------------------------------------------------
 
-while read -a X; do
-	if [ "${X[1]/\"}${X[2]}${X[3]}" == "i3barforoutput" ]; then
-		if [ -x /usr/bin/transset ]; then
-			/usr/bin/transset $1 -i "${X[0]}"
-		elif [ -x /usr/bin/transset-df ]; then
-			/usr/bin/transset-df $1 -i "${X[0]}"
+if [ -x /usr/bin/xwininfo ]; then
+	while read -a X; do
+		if [ "${X[1]/\"}${X[2]}${X[3]}" == "i3barforoutput" ]; then
+			if [ -x /usr/bin/transset ]; then
+				/usr/bin/transset $1 -i "${X[0]}"
+			elif [ -x /usr/bin/transset-df ]; then
+				# This is to support Arch.
+				/usr/bin/transset-df $1 -i "${X[0]}"
+			fi
 		fi
-	fi
-done <<< "$(/usr/bin/xwininfo -root -all)"
+	done <<< "$(/usr/bin/xwininfo -root -all)"
+else
+	printf "ERROR: Dependency '/usr/bin/xwininfo' not met.\n" 1>&2
+fi
 
 # vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
